[package]
name = "chicago_skyline"
version = "0.0.1"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
reqwest = { version = "0.12.15", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
